# Конфигурационный файл для развертывания на Railway

[build]
builder = "nixpacks"  # Система сборки для приложения

[deploy]
startCommand = "npm start"  # Команда для запуска приложения после сборки

[env]
PORT = "3000"  # Порт, на котором будет работать приложение
